### PR TITLE
Add 2.4ghz SNES Classic Support... needs deliberation

### PR DESCRIPTION
**Pull request by nullstalgia**
Hi, me again :eyes: 

So I grabbed [these off Amazon](https://www.amazon.com/gp/product/B07FCXL2VV/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1), and they are a MESS.

Trigger data is in Control Bytes 4 and 5, they have a weird ID, etc

So you *can* merge this if you like, but I'm not too sure.

Additionally, you may remember issue #46 of mine. I contacted 8BitDo about adding analog stick support to the adapter, and they may consider it.

The reason I bring it up, is because of how ManipulateThirdPartyData forces a set state of analogs, and this controller does its own BS...

I'll keep you updated. :)

### CODE REVIEW

**Comment by nullstalgia** [comment]
Yeah, out of the 2-pack of controllers I got, only 1 works.. Not sure if this is worth our time. :laughing: 

It's something to take into consideration, though.

**Comment by dmadison** [comment]
This is one of the reasons I was hesitant to add the "fixThirdParty" functions in the first place. Once you start supporting bizzarro controllers which don't follow the OEM standard, it opens the floodgates for all sorts of cheap variations that don't follow the standard in their own strange ways. Having the default data being slightly different is one thing, reporting different ID bytes and having different data mappings is another.

I'm going to say that controllers like these, with their own unique quirks, would be better served as a separate controller type. Although that too will get messy quickly if you try to support all of the poorly engineered controllers out there...

**Comment by nullstalgia** [comment]
I 100% agree with the "floodgates" opening.

It is possible, since GetControlData is already public, it could be something shown in an example.

For example: on reset, it can check the control bytes against a signature the user set (basically a copy of the current isThirdParty, but made by the user), it sets a global Boolean to true, then that can be passed to fixNESThirdParty's force argument.

**Comment by dmadison** [comment]
That's still quite a messy solution though, especially if the identity bytes differ since that will cause the `ClassicController` object to report communication errors.

I think the real answer is that quirky controllers that don't match Nintendo's data maps and identity strings need to be defined as their own controller types and treated like the off-brand imitations they are. But I also don't want to play whack-a-mole with trying to identify which NES/SNES controller variant came from which cheap Chinese dropshipper, and trying to match that to a named class.

**Comment by nullstalgia** [comment]
Yeah, I see your point more clearly now. 

Looking briefly at the Amazon listings, they all seem to have the same "WIRELESS GAMEPAD" font and such on it, suggesting, *but not guaranteeing,* a carbon copy product.

So at that point, it becomes an issue of not just time and money, but also sanity. (Look back at the fact that one of the controllers I received has a dodgy battery)

What do you think is the best solution for this? First thing that came to mind after your "that will cause the ClassicController object to report communication errors" comment, is that one could force set a type. But that would require weird explanations, more globals, and a waste of time... yeah not my best idea.

Obviously this isn't a widespread issue with the users of the library, as only issue 33 (not tagging on purpose), and my own issue bring up 3rd party controllers. Is just ignoring it the best course of action?

Apologies if this is a waste of time for you, by the by!

**Comment by dmadison** [comment]
You have to be careful with that, because often times Chinese companies will buy the injection molded shells from one factory and stick their own electronics in them since custom electronics are much cheaper to produce. Not to mention that sellers often re-use other product images even if they don't perfectly match their product. It's impossible to say whether the behavior would match without testing with a few different "brands", and even then it's hard to clearly identify exactly *what* it is to the user if the standard `ClassicController` object won't work with it. Particularly if we don't know the manufacturer or the creator of the original design.

My gut reaction is to ignore it. Well-made imitation controllers match the Classic Controller perfectly and work without issue. Poorly made imitation controllers appear to have the same data offset and are easily (although crudely) fixed with the `fixThirdPartyData` function. I don't have much interest in accommodating the poorly made *and* niche controllers that neither identify themselves properly nor map their data correctly.

I think it's an important conversation to be had, but I don't think there is any good solution for adding support for those types of controllers. Since they are still being manufactured and bought they presumably do *work* in some capacity with the mini consoles, so it's possible that their data is only reported improperly in the unencrypted communication mode.

A more comprehensive solution might be to add encrypted comms support to the library as a whole, but that's a significant amount of work. And since nearly all of the controllers work properly in unencrypted mode I don't have any interest in doing it right now.

**Comment by nullstalgia** [comment]
> My gut reaction is to ignore it. Well-made imitation controllers match the Classic Controller perfectly and work without issue.

I agree, especially with the well-made comment.

And I guess we're lucky that there even *is* an unencrypted mode. I wonder why, however.

Anyway, unless you feel further discussion is necessary, feel free to close this up. :)

**Pull request closed without merging**
