### PR TITLE
uDraw Tablet support and demos

### PR DESCRIPTION
**Pull request by nullstalgia**
This series of commits includes PR #55, and support for Ubisoft's uDraw Tablet. 

image

[It is possible that the Drawsome tablet is compatible](https://wiibrew.org/wiki/Wiimote/Extension_Controllers/Drawsome_Tablet), but as I do not have one to test with, I can not confirm this.

image

### CODE REVIEW

**Comment by dmadison** [comment]
Nice! This looks very well done. I have no experience with these tablets so I'm relying on your expertise. A few changes and notes:

What are `button1` and `button2` in this context? Is there a better name for these?

I see that the pressure has two levels as signified by the "tip" bit. Is there a physical detent when using the pen to signify that transition? Would it make more sense to add the "tip" bit as the 9th bit of the pen pressure instead of using it as a separate "button"?

I understand the usefulness of the "Mouse" example but it's a bit of an odd man out, since all of the other devices are game controllers as well and don't have corresponding HID examples. Is there a compelling reason to keep this example in particular?

Most of the non-Nintendo controller class names are generalized, and I'm a bit hesitant to put everything under the `uDrawTablet` name since the Drawsome tablet exists. I know you don't have a Drawsome tablet on hand, but from your testing do you think the Drawsome tablet's data is mapped similarly to the uDraw?

**Comment by nullstalgia** [comment]
Thank you! 

Button 1 and 2 are as shown here:
image

And I was having a dilemma with that wording too. But I couldn't think of a better way to put it. Bottom/Top button? Lower/Upper?

And yes, the tip does have a physical "bump" or "detent" when it reaches that second 0-255 phase, which is why I left it as a separate button :)

Still not sure how to word it properly.

For the mouse example, I understand it's a little "out of scope," but one of the main uses for tablets like this *is* as a mouse. In fact, one of the sources of information and inspiration I used was this repo where the dev made a arduino > serial > linux tablet driver. That requires Python and custom linux services, where as mine just requires the bog standard Mouse library.

https://github.com/mwvent/wii_udraw2arduino2linux

And as for the Drawesome... since I don't have much else going on, I ordered one off of eBay and it should be here by end of week.

**Comment by dmadison** [comment]
I think for the side switch, "Upper/Lower" is more descriptive than "1 and 2". And since those are the only two "buttons" aside from the tip, I think we shouldn't need to include "side" in there anywhere.

>And yes, the tip does have a physical "bump" or "detent" when it reaches that second 0-255 phase, which is why I left it as a separate button :)

Ah okay, that's good. In that case I agree, the "tip" should be a separate button function.

I try to veer away from assuming how the user wants to use the data, so I'm split on whether to leave the 0-255 ranges separate or combine them. On the one hand it's not very intuitive to say that `penPressure` resets halfway through the range, and on the other if we mapped it to 9 bit it would be strange to say that `penPressure` only "clicks" starting at halfway through the range.

My gut says to keep it as-is, and instead change the examples so they reflect that `penPressure` is relative to whether or not the tip is "pressed", instead of showing a map of the whole range.

>For the mouse example, I understand it's a little "out of scope," but one of the main uses for tablets like this is as a mouse. 

I completely understand that, I just don't think it's a good fit as an *example*. None of the other controllers in the library have HID examples even though their primary (although not exclusive) use is as USB controllers. There are two reasons for this:

First, it requires that users have USB-capable Arduino boards. That tends to lead to a lot of unnecessary noise from users who are trying the "included examples" on Unos and Nanos, get frustrated that they don't work, and blame the library for their trouble. It's much nicer when all of the examples are board-agnostic.

Second, those programs tend not to be so much *examples* as they are *finished programs* - or attempts to be ones. But because library examples are written to be simple and easy to understand for novices, examples that are "complete solutions" to problems tend to be half-baked. Which leads to issue reports and feature requests to make the "example" sketch more feature-complete as a finished solution, rather than being an example for how to use the library.

In short: in my mind the examples in the library should be just that - examples for how to use the library's features and functions, not as complete solutions to a problem. I hope that's clear.

Perhaps it would be better to rewrite the `Demo` sketch to include some of the Mouse features, such as delta coordinates?

>And as for the Drawsome... since I don't have much else going on, I ordered one off of eBay and it should be here by end of week. So we can keep this pull as Open until I receive and test it.

Nice! Thank you, that's going to be a big help.

>If it is incompatible, however, what do you think is the best way to go about it? Have a Drawsome controller profile? What if just one bit is different? Or the X and Y are swapped, but the rest is the same?

We'll cross that bridge when we get there, but it depends on the significance of the differences. My guess is that we may end up with two separate controller classes and types, using a common parent.

**Comment by nullstalgia** [comment]
So, update:

buttonLower and buttonUpper are done

---

buttonTip has been removed entirely in exchange for it being the most significant bit of penPressure, raising it's resolution to 0-512.

It turns out the physical "button" is when the pen starts registering pressure above the minimum (in my case, 8). And even when considering using it as a "hard press" sensor, the pressure needed doesn't make sense. As such, I decided to cut out buttonTip.

---

The item has shipped and is estimated for Friday, so hopefully I can get some work done during the quarantine and DOOM Eternal's release. :)

---

If they are incompatible, can I rely on you (or an example for me to reference) for the common parent implementation? C++ is not my forte. :P

**Comment by dmadison** [comment]
>It turns out the physical "button" is when the pen starts registering pressure above the minimum (in my case, 8), way before that bit is changed at all. And even when considering using it as a "hard press" sensor, the pressure needed doesn't make sense. As such, I decided to cut out buttonTip.

Ah that's a shame. Yeah, then it does sound like that's the way to go.

>The item has shipped and is estimated for Friday, so hopefully I can get some work done during the quarantine and DOOM Eternal's release. :)

Looking forward to it :)

>If they are incompatible, can I rely on you (or an example for me to reference) for the common parent implementation? C++ is not my forte. :P

Absolutely! Just let me know what the data shows and we can go from there. I think if you enable "Allow edits from maintainers" on the pull request I can make the commits myself.

**Comment by nullstalgia** [comment]
Big news incoming!

Due to this research, I found something *big.* To me, anyway. I'll save it for last though. ;)

So I got the tablet in, and it didn't do shiz when I plugged it in. I also noticed the pen had no buttons on it, despite the retail box showing 2 like the uDraw..

Anyway, I kept browsing Google Images and I came across this article about this exact thing.

[https://www.raphnet.net/divers/wii_graphics_tablets/index_en.php](https://www.raphnet.net/divers/wii_graphics_tablets/index_en.php)

(He kept the tip as a button, oddly enough.)

In the article he describes the data format:

image

But in order to have the tablet function, you need to write to 2 addresses.

>So the magic recipe to enable the tablet appears to be:
>
> 1. Write 0x01 to address 0xFB
> 2. Write 0x55 to address 0xF0

So, I'll leave this part to you unless you need more information / need me to test :)

---

But I found something wacky, that I may bring up in an issue since I'm not familiar with how to implement it myself at this time. 

# We can remove the fixThirdPartyData feature entirely.

(maybe)

The fact that those controllers have 2 extra bytes is *BY DESIGN* of the NES and SNES Classic!

[https://www.raphnet-tech.com/support/classic_controller_high_res/index.php](https://www.raphnet-tech.com/support/classic_controller_high_res/index.php)

[https://github.com/raphnet/extenmote/blob/master/notes_nes_classic.txt](https://github.com/raphnet/extenmote/blob/master/notes_nes_classic.txt)

I'm not sure if this is implemented by third party pro controllers, but I will sure as hell test it for you if you wish.

**Comment by dmadison** [comment]
Okay, so the Drawsome tablet has different ID bytes, a different data layout, and requires some extra register writes before it works? In that case it would be best as a different controller class entirely. You can start putting that together yourself as a separate branch / pull request if you'd like.

Good sleuthing work on the Classic Controller "high resolution" mode. I'll have to think about how best to implement that...

Both the Drawsome tablet and the "high resolution" mode will require extra register writes outside of the normal flow of the library. I think I'll have to rewrite the `ExtensionController` class a bit to make that feasible.

---

In the meantime, let's get this uDraw controller buttoned up and merged. I've never tried adding any "maintainer" commits before, but I think I can recommend changes to your branch and you can accept the commits. Once I'm done polishing I'll have you test with the controller one last time, and then we can merge the PR.

**Comment by dmadison** [comment]
Okay, that should be all of them. It's a lot of commits but they're all tiny tweaks. Most changes were just style and polish, although I did add the pen's X/Y coordinates to the `Demo` example and change the code behind the `penDetected` function.

Please check both examples against your tablet and see if the uDraw class still works as expected. Thanks!

**Comment by nullstalgia** [comment]
Still seems to work fine! If any issues arise, I'll let you know/pull in some changes.

**Comment by dmadison** [comment]
Awesome! Merging now. Thank you!

**Pull request merged**
